services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: dq
      POSTGRES_DB: dqdb
    ports:
      - "5432:5432"
    volumes:
      - dqdb_data:/var/lib/postgresql/data

volumes:
  dqdb_data: